sudo: false
matrix:
  allow_failures:
    - os: osx
    - python: 3.8-dev
    - env: TRAVIS_NODE_VERSION=12
  include:
    - language: python
      dist: trusty
      python: 3.4
      env:
        - TRAVIS_NODE_VERSION=8
        - BROWSER=PhantomJS
    - language: python
      python: 3.5
      dist: bionic
      services:
        - xvfb
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      env:
        - TRAVIS_NODE_VERSION=10
        - BROWSER=Chrome
    - language: python
      python: 3.6
      dist: bionic
      services:
        - xvfb
      env:
        - TRAVIS_NODE_VERSION=10
        - BROWSER=Firefox
    - language: python
      python: 3.7
      sudo: true
      dist: bionic
      services:
        - xvfb
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      env:
        - TRAVIS_NODE_VERSION=10
        - BROWSER=Chrome
    - language: python
      python: 3.8-dev
      sudo: true
      dist: bionic
      services:
        - xvfb
      env:
        - TRAVIS_NODE_VERSION=12
        - BROWSER=Firefox
    - language: python
      dist: trusty
      python: pypy3
      env:
        - TRAVIS_NODE_VERSION=10
        - BROWSER=PhantomJS
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
    # test different versions of Node.js on osx
    - language: node_js
      node_js: 8
      os: osx
      env:
        - TRAVIS_PYTHON_VERSION=3.5.7
        - BROWSER=PhantomJS
    - language: node_js
      node_js: 10
      os: osx
      env:
        - TRAVIS_PYTHON_VERSION=3.6.9
        - BROWSER=Safari
    - language: node_js
      node_js: 12
      os: osx
      env:
        - TRAVIS_PYTHON_VERSION=3.7.3
        - BROWSER=Safari

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update || brew update ;
      brew install pyenv ;
      brew outdated pyenv || brew upgrade pyenv ;
      pyenv install $TRAVIS_PYTHON_VERSION ;
      pyenv global $TRAVIS_PYTHON_VERSION ;
      eval "$(pyenv init -)" ;
      python --version ;
      python -m pip install --user virtualenv ;
      python -m virtualenv ~/.venv ;
      source ~/.venv/bin/activate ;
    else
      export DISPLAY=:99.0 ;
      sh -e /etc/init.d/xvfb start ;
      rm -rf ~/.nvm ;
      git clone https://github.com/creationix/nvm.git ~/.nvm ;
      (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` );
      source ~/.nvm/nvm.sh ;
      nvm install "$TRAVIS_NODE_VERSION" ;
    fi
  - node --version
  - npm --version

install:
  # git+https link support requires pip/setuptools be updated manually?
  - pip install -U coverage flake8 pip setuptools
  # need this to avoid ambiguity later
  - pip install -U calmjs.dev calmjs.rjs calmjs.webpack
  - pip install -e .[dev,rjs,webpack]

  # doing the env in this directory to save build time/bandwidth, as the
  # same environment will be used for both Python and JavaScript tests.
  - calmjs npm --install nunja.stock[dev,rjs,webpack] -w -D
  # out-of-band installation of platform specific dependencies
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm install karma-safari-launcher ;
    fi
  - export CALMJS_TEST_ENV=.
script:
  - flake8 setup.py src
  - coverage run --include=src/* -m unittest nunja.stock.tests.make_suite

  # generate bundle/tests
  - mkdir manual
  - calmjs webpack nunja -w --export-target=nunja.webpack.js

  # eslint 3 only works in nodejs 4+
  # not linting while prototyping a new build system.
  # - if [[ "$TRAVIS_NODE_VERSION" != "0.12" ]]; then
  #     ./node_modules/.bin/eslint "src/**/*.js" ;
  #   fi
  - calmjs karma --artifact=nunja.webpack.js -c --cover-test --browser=$BROWSER webpack nunja.stock --sourcepath-method=explicit -w
  - coverage report -m

  # For proper testing of source coverage, provide artifact for nunja.
  - calmjs rjs --optional-advice=nunja --source-registry=calmjs.module nunja
  - calmjs karma --artifact=nunja.js --browser=$BROWSER --coverage --cover-test rjs --sourcepath-method=explicit --build-dir=manual -w nunja.stock

  # Finally, for the full standalone artifact for just this package
  # - calmjs karma --artifact=nunja.js --browser=$BROWSER --coverage --cover-test rjs --sourcepath-method=explicit --bundle-map-method=none -w nunja.stock

  # build all artifacts
  - calmjs artifact build nunja.stock
  # test all artifacts
  - calmjs artifact karma --browser=$BROWSER nunja.stock

after_success:
  # only submit coverage when testing under linux.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      rvm default;
      gem install coveralls-lcov;
      export PROJ_DIR=`pwd`/;
      export PATH=$PATH:`pwd`/node_modules/.bin;
      npm install remap-istanbul;
      pip install coveralls;
      cd manual;
      remap-istanbul -i ../coverage/coverage.json -t lcovonly -o remapped.lcov;
      sed -i "s#SF:../#SF:#" remapped.lcov;
      sed -i "s#SF:${PROJ_DIR}#SF:#" remapped.lcov;
      cd ..;
      echo "running coveralls-lcov conversion";
      coveralls-lcov -v -n manual/remapped.lcov > coverage.json ;
      echo "running coveralls with merge";
      coveralls --merge=coverage.json ;
    fi

branches:
  only:
    - testing
    - master
    - 1.0.x
