environment:
  matrix:
    - PYTHON: "C:\\Python27"
      nodejs_version: "8"
      BROWSER: "Chrome"
    - PYTHON: "C:\\Python34"
      nodejs_version: "10"
      BROWSER: "Chrome"
    - PYTHON: "C:\\Python35"
      nodejs_version: "10"
      BROWSER: "Firefox"
    - PYTHON: "C:\\Python36"
      nodejs_version: "10"
      BROWSER: "IE"
    - PYTHON: "C:\\Python37"
      nodejs_version: "12"
      BROWSER: "PhantomJS"
matrix:
  allow_failures:
    - BROWSER: "IE"

install:
  - choco install firefox
  - choco install googlechrome
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node $env:nodejs_version
  - pip install virtualenv
  - virtualenv --clear venv
  - "venv\\Scripts\\activate.bat"

  - pip install coverage flake8
  # need this to avoid ambiguity later
  - pip install -U calmjs.dev calmjs.rjs calmjs.webpack
  - pip install -e .[dev,rjs,webpack]

  # doing the env in this directory to save build time/bandwidth
  - calmjs npm --install nunja.stock[dev,webpack,rjs] -w -D
  # out of band installation for IE launcher.
  - npm install karma-ie-launcher
  - "SET CALMJS_TEST_ENV=."

test_script:
  - coverage run -m unittest nunja.stock.tests.make_suite
  - coverage report -m --include=src/*

  # with RequireJS
  - calmjs rjs nunja -w --export-target=nunja.js
  - calmjs karma --artifact=nunja.js -c --cover-test --browser=%BROWSER% rjs nunja.stock --sourcepath-method=explicit -w

  # with webpack
  - calmjs webpack nunja -w --export-target=nunja.webpack.js
  - calmjs karma --artifact=nunja.webpack.js -c --cover-test --browser=%BROWSER% webpack nunja.stock --sourcepath-method=explicit -w

  # build all artifacts
  - calmjs artifact build nunja.stock
  # test all artifacts
  - calmjs artifact karma --browser=%BROWSER% nunja.stock

artifacts:
  - path: dist\*

build: off
